### ISSUE TITLE
Please use release tags

### ISSUE THREAD

**Issue by tillea** [daleroberts/hdmedians#2]
Hi,
I intend to package hdmedians for official Debian. It would help if you would consider adding release tags to enable users to decide what is just a develoment commit and what is a real release fit for distribution.
Thanks a lot for considering, Andreas.

**Comment by greyltc** [comment]
@daleroberts please use github's release feature to tag commits that correspond to stable releases

**Comment by tillea** [comment]
There are release tags now.  Thanks for doing so.
